// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadSearchPreview = { "kind": "conversation", userMessage: string, assistantMessage: string | null, } | { "kind": "contentMatch", snippet: string, };
